import { Client } from "@/types/client";

export const clients: Client[] = [
  {
    id: 20,
    name: "John Doe",
    type: "Individual",
    email: "johndoe@email.com",
    createdAt: "2023-10-01",
    updatedAt: "2023-12-01",
    updatedBy: "Admin",
    status: "Active",
  },
  {
    id: 21,
    name: "Jane Smith",
    type: "Company",
    email: "contact@janesmith.com",
    createdAt: "2023-08-15",
    updatedAt: "2023-11-22",
    updatedBy: "System",
    status: "Inactive",
  },
  {
    id: 22,
    name: "Test User",
    type: "Individual",
    email: "testuser@email.com",
    createdAt: "2023-09-05",
    updatedAt: "2023-12-10",
    updatedBy: "John Doe",
    status: "Active",
  },
  {
    id: 23,
    name: "Acme Corp",
    type: "Company",
    email: "info@acme.com",
    createdAt: "2023-07-25",
    updatedAt: "2023-10-18",
    updatedBy: "Jane Smith",
    status: "Active",
  },
  {
    id: 24,
    name: "Foo Bar",
    type: "Individual",
    email: "foobar@email.com",
    createdAt: "2023-09-30",
    updatedAt: "2023-11-05",
    updatedBy: "Moderator",
    status: "Inactive",
  },
];
